### ISSUE TITLE
QAF Integration With Cucumber Runner(6.8.1) and testNG(7.1.0)

### ISSUE THREAD

**Issue by aruna3390** [qmetry/qaf-cucumber#11]
Hi Team,

I am trying to integrate QAF with my existing Cucumber-TestNG project which uses Cucumber Runner class to run my tests with excel sheets(@datafile) instead of examples as data requirement is heavy

I am using QAF-CUCUMBER 3.0.0 for my integration and I am getting below error.
Can someone help me with the integration? Is QAF-CUCUMBER compatible with TestNG 7 and Cucumber 6.8.1?

**_Error log:_**
12:19:23.594 [main] ERROR com.qmetry.qaf.automation.util.PropertyUtil - resources\application.properties (The system cannot find the path specified)
12:19:23.607 [main] ERROR com.qmetry.qaf.automation.core.ConfigurationManager - C:\Ark\GitNew\itp-hits-ci-ui-test\resources not exist!
FAILED CONFIGURATION: @BeforeClass setUpClass
java.lang.NullPointerException
	at com.qmetry.qaf.automation.testng.pro.QAFTestNGListener.beforeInvocation(QAFTestNGListener.java:174)
	at org.testng.internal.invokers.InvokedMethodListenerInvoker.invokeListener(InvokedMethodListenerInvoker.java:57)

After creating blank resources\application.properties , still I got above NullPointerException

**Comment by cjayswal** [comment]
Below are few facts:
- Cucumber doesn't support examples/testdata outside feature file (BDD or BDD2 syntax)
- BDD2 is supported using QAF-cucumber with **cucumber 5**.
- `AbstractTestNGCucumberTests` will not support BDD2 syntax. If you want to use TestNG runner, you need to use either `BDDTestFactory2` `CucumberScenarioFactory` [refer support of cucumber lifecycle with Testng](https://github.com/qmetry/qaf-cucumber/issues/10)

You can try with cucumber 5 with QAF-3.0.1 using  `CucumberScenarioFactory`

**Comment by bansalnitin92** [comment]
hi @cjayswal how can i use CucumberScenarioFactory to use BDD2 features like read from External files
